-- 1. Добавить разаработчикам поле (salary - зарплата). 

use homework_1;

ALTER TABLE developers 
	ADD DEVELOPER_SALARY INT(6) DEFAULT NULL
	AFTER DEVELOPER_LASTNAME;

UPDATE developers SET DEVELOPER_SALARY=2000 WHERE DEVELOPER_LASTNAME ='Shylo' AND DEVELOPER_NAME='Ihor';
UPDATE developers SET DEVELOPER_SALARY=1100 WHERE DEVELOPER_LASTNAME = 'Olifer' AND DEVELOPER_NAME LIKE 'Anna';
UPDATE developers SET DEVELOPER_SALARY=800 WHERE DEVELOPER_LASTNAME = 'Hizun' AND DEVELOPER_NAME LIKE 'Yrii';
UPDATE developers SET DEVELOPER_SALARY=850 WHERE DEVELOPER_LASTNAME = 'Gingembre' AND DEVELOPER_NAME LIKE 'Guilaume';
UPDATE developers SET DEVELOPER_SALARY=900 WHERE DEVELOPER_LASTNAME = 'Ivashkov' AND DEVELOPER_NAME LIKE 'Denis';
UPDATE developers SET DEVELOPER_SALARY=1000 WHERE DEVELOPER_LASTNAME = 'Rosovskiy' AND DEVELOPER_NAME LIKE 'Pavel';
UPDATE developers SET DEVELOPER_SALARY=1100 WHERE DEVELOPER_LASTNAME = 'Kontar' AND DEVELOPER_NAME LIKE 'Maryna';

SELECT * FROM developers;