-- 4. Добавить поле (cost - стоимость) в таблицу Projects .

use homework_1;

ALTER TABLE projects 
	ADD PROJECT_COST INT(5) DEFAULT NULL
	AFTER PROJECT_NAME;

UPDATE projects SET PROJECT_COST=10000 WHERE PROJECT_ID=1;
UPDATE projects SET PROJECT_COST=15000 WHERE PROJECT_ID=2;
UPDATE projects SET PROJECT_COST=20000 WHERE PROJECT_ID=3;
UPDATE projects SET PROJECT_COST=40000 WHERE PROJECT_ID=4;
UPDATE projects SET PROJECT_COST=105000 WHERE PROJECT_ID=5;

SELECT * FROM projects; 