CREATE DATABASE chat;

use chat;

-- 
CREATE TABLE USERS(
LOGIN VARCHAR(255) NOT NULL,
PASS VARCHAR(255) NOT NULL,
USERNAME VARCHAR(255) NOT NULL,
REGISTRATION_DATE timestamp NOT NULL,
PRIMARY KEY(LOGIN)
);

CREATE TABLE CHAT(
CHAT_NAME VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
PRIMARY KEY(CHAT_NAME)
);

CREATE TABLE MESSAGE(
FK_MESSAGE_USER_LOGIN VARCHAR(255) NOT NULL,
FK_MESSAGE_CHAT_NAME VARCHAR(255) NOT NULL,
MESSAGE_TEXT varchar(255),
MESSAGE_DATE timestamp NOT NULL,

FOREIGN KEY (FK_MESSAGE_USER_LOGIN) REFERENCES USERS(LOGIN),
FOREIGN KEY (FK_MESSAGE_CHAT_NAME) REFERENCES CHAT(CHAT_NAME),

PRIMARY KEY(FK_MESSAGE_USER_LOGIN,FK_MESSAGE_CHAT_NAME)
);

