CREATE DATABASE homework_1;

CREATE TABLE homework_1.developers(
DEVELOPER_ID INT(11) NOT NULL  auto_increment,
DEVELOPER_NAME VARCHAR(255) NOT NULL,
DEVELOPER_SURNAME VARCHAR(255) NOT NULL,
PRIMARY KEY(DEVELOPER_ID)
);
 
 CREATE TABLE homework_1.skills(
 SKILL_ID INT(11) NOT NULL auto_increment,
 SKILL_NAME VARCHAR(255) NOT NULL,
 PRIMARY KEY(SKILL_ID)
 );

CREATE TABLE homework_1.companies(
 COMPANY_ID INT(11) NOT NULL auto_increment,
 COMPANY_NAME VARCHAR(255) NOT NULL,
 PRIMARY KEY(COMPANY_ID)
 );
 
CREATE TABLE homework_1.customers(
 CUSTOMER_ID INT(11) NOT NULL auto_increment,
 CUSTOMER_NAME VARCHAR(255) NOT NULL,
 PRIMARY KEY(CUSTOMER_ID)
 );
 
 CREATE TABLE homework_1.projects(
 PROJECT_ID INT(11) NOT NULL auto_increment,
 PROJECT_NAME VARCHAR(255) NOT NULL,
 COMPANY_ID INT,
 CUSTOMER_ID INT,
 PRIMARY KEY(PROJECT_ID),
 FOREIGN KEY (COMPANY_ID) REFERENCES 
			homework_1.companies(COMPANY_ID),
 FOREIGN KEY (CUSTOMER_ID) REFERENCES 
			homework_1.customers(CUSTOMER_ID)
 );
 
 CREATE TABLE homework_1.developer_skill(
DEVELOPER_ID INT(11) NOT NULL,
SKILL_ID INT(11) NOT NULL,
 FOREIGN KEY (DEVELOPER_ID) REFERENCES homework_1.developers(DEVELOPER_ID),
 FOREIGN KEY (SKILL_ID) REFERENCES homework_1.skills(SKILL_ID)
);

CREATE TABLE homework_1.developer_project(
DEVELOPER_ID INT(11) NOT NULL,
PROJECT_ID INT(11) NOT NULL,
FOREIGN KEY (DEVELOPER_ID) REFERENCES homework_1.developers(DEVELOPER_ID),
FOREIGN KEY (PROJECT_ID) REFERENCES homework_1.projects(PROJECT_ID)
);

